apiVersion: apps/v1
kind: Deployment
metadata:
 name: kibana
spec:
 selector:
  matchLabels:
   app: kibana
 template:
  metadata:
   labels:
    app: kibana
    tier: frontend
  spec:
    containers:
    - name: kibana
      image: docker.elastic.co/kibana/kibana:7.16.3
      ports:
      - containerPort: 5601

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    targetPort: 5601
  selector:
    app: kibana
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-internal
spec:
  ports:
  - port: 5601
    targetPort: 5601
  selector:
    app: kibana
    tier: frontend
---
